server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # C'EST LA LIGNE MAGIQUE POUR REACT ROUTER :
        try_files $uri $uri/ /index.html;
    }
}